spring.datasource.url=jdbc:mysql://root:VmnfDVveRbsRsTNJDmnuhKpvvYVhpQHv@yamanote.proxy.rlwy.net:24463/railway
spring.datasource.username=root
spring.datasource.password=VmnfDVveRbsRsTNJDmnuhKpvvYVhpQHv   

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
